ALTER TYPE "LeaveStatus" ADD VALUE 'PENDING_HR';
ALTER TYPE "LeaveStatus" ADD VALUE 'PENDING_SUPERADMIN';
ALTER TYPE "LeaveStatus" ADD VALUE 'HR_APPROVED';
ALTER TYPE "LeaveStatus" ADD VALUE 'FINAL_APPROVED';
ALTER TYPE "LeaveStatus" ADD VALUE 'REJECTED_BY_HR';
ALTER TYPE "LeaveStatus" ADD VALUE 'REJECTED_BY_SUPERADMIN';
ALTER TYPE "LeaveStatus" ADD VALUE 'CANCELLED';
